spring:
  application:
    name: zbank-fraud-engine
  
  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/zbank_fraud
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Automatically creates tables for local dev
    show-sql: true      # Prints SQL queries to the console for debugging
    properties:
      hibernate:
  
  kafka:
      bootstrap-servers: localhost:9092
      producer:
        # Automatically convert our Java Records into JSON before sending to Kafka
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
        # Automatically convert incoming JSON back into Java Records
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        group-id: zbank-fraud-group
        properties:
          spring.json.trusted.packages: "*"    
